apiVersion: v1
kind: ReplicationController
metadata:
  name: myvertex-rc
spec:
  replicas: 3
  selector:
    app: myvertexapp
  template:
    metadata:
      name: complexpod
      labels:
        app: myvertexapp
    spec:
      containers:
        - name: mynginx-container
          image:  gouriboga/myjavaimage7dec22:2
          ports:
            - containerPort: 8080
