apiVersion: v1
kind: ReplicationController
metadata:
  name: myvertex-rc
spec:
  replicas: 5
  selector:
    app: myvertexapp
    Version: 2.6.2
  template:
    metadata:
      labels:
        app: myvertexapp
        Version: 2.6.2
    spec:
      containers:
        - name: mynginx-container
          image: gouriboga/myjavaimage18nov22:1
          ports:
            - containerPort: 8080
